spring.application.name=recepies

# 1. הגדרת החיבור לבסיס הנתונים בזיכרון (נקרא לו recipe_db)
spring.datasource.url=jdbc:h2:mem:recipe_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 2. פקודה ל-Hibernate לייצר את הטבלאות אוטומטית בכל הפעלה מחדש
spring.jpa.hibernate.ddl-auto=create-drop

# 3. הפעלת ממשק ניהול גרפי (Console) כדי שתוכלו לראות את הטבלאות בדפדפן
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 4. הצגת שאילתות ה-SQL שהמערכת מריצה בתוך ה-Terminal (מעולה לניקוי באגים)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true